# Generated by Django 6.0.2 on 2026-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва завдання')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Виконано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
